import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import{LayoutDashboard,CalendarDays,Package,Plus,Download,RefreshCw,Settings,Search,ChevronDown,ChevronRight,TrendingUp,TrendingDown,TriangleAlert,CheckCircle2,X,Cloud,MoreHorizontal,ArrowUpRight,WalletCards,ShoppingBag,Percent,Target,SlidersHorizontal,Box,Link2,Unlink,FileSpreadsheet}from'lucide-react';
import'./styles.css';
import{api}from'./api';

const products=[
 {sku:'а3',name:'Длинные мужские Белые',sold:42,revenue:39018,ads:4050,extra:760,profit:2940.81,margin:7.54,cost:268,price:929,roi:31.8,stock:null,link:'Связан',scheme:'FBO'},
 {sku:'с1',name:'Мужские носки набор 10 пар',sold:39,revenue:36543,ads:3880,extra:1200,profit:2564.22,margin:7.02,cost:281,price:937,roi:28.1,stock:null,link:'Связан',scheme:'FBO'},
 {sku:'р2',name:'Носки мужские спортивные',sold:35,revenue:32165,ads:3400,extra:550,profit:2301.7,margin:7.16,cost:255,price:919,roi:25.8,stock:null,link:'Связан',scheme:'FBS'},
 {sku:'0 1',name:'Носки короткие белые',sold:31,revenue:27869,ads:3620,extra:980,profit:1642.5,margin:5.89,cost:249,price:899,roi:22.4,stock:null,link:'Связан',scheme:'FBO'},
 {sku:'б4',name:'Длинные мужские Чёрные',sold:29,revenue:27231,ads:3150,extra:640,profit:1421.11,margin:5.22,cost:274,price:939,roi:18.9,stock:null,link:'Связан',scheme:'FBO'},
 {sku:'м7',name:'Носки базовые серые',sold:24,revenue:21576,ads:3890,extra:890,profit:-422.3,margin:-1.96,cost:290,price:899,roi:-5.1,stock:null,link:'Не найден',scheme:'FBS'},
 {sku:'0 5-1',name:'Носки укороченные 5 пар',sold:18,revenue:14382,ads:2760,extra:1100,profit:-936.4,margin:-6.51,cost:null,price:799,roi:null,stock:null,link:'Не найден',scheme:'FBO'},
];
const fmt=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2,minimumFractionDigits:2}).format(n)+' ₽';
const pct=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2,minimumFractionDigits:2}).format(n)+'%';
const days=[{d:'01 июл',revenue:649721,profit:25379},{d:'02 июл',revenue:627729,profit:22741}];

function App(){
 const[page,setPage]=useState('Главная');const[expense,setExpense]=useState(false);const[settings,setSettings]=useState(false);const[toast,setToast]=useState('');const[extra,setExtra]=useState(23010);const[tab,setTab]=useState('Товары');
 const notify=t=>{setToast(t);setTimeout(()=>setToast(''),2500)};
 const exportXlsx=()=>{window.location.assign(api.exportUrl);notify('Отчёт Excel сформирован на сервере')};
 const saveExpense=async v=>{try{await api.addCost({day:'2026-07-02',kind:'extra',amount:Number(v),comment:'Добавлено из интерфейса'});setExtra(extra+Number(v));setExpense(false);notify('Расход сохранён, показатели пересчитаны')}catch(e){notify(e.message)}};
 return <div className="app"><Sidebar page={page} setPage={setPage}/><main><Header page={page} onExpense={()=>setExpense(true)} onExport={exportXlsx} onSettings={()=>setSettings(true)} notify={notify}/>{page==='Главная'?<Dashboard extra={extra}/>:page==='Ежедневный контроль'?<Daily tab={tab} setTab={setTab}/>:<Catalog/>}</main>{expense&&<ExpenseModal close={()=>setExpense(false)} save={saveExpense}/>} {settings&&<SettingsModal close={()=>setSettings(false)} notify={notify}/>} {toast&&<div className="toast"><CheckCircle2 size={18}/>{toast}</div>}</div>
}
function Sidebar({page,setPage}){const nav=[['Главная',LayoutDashboard],['Ежедневный контроль',CalendarDays],['Товары и юнит-экономика',Package]];return <aside><div className="brand"><div className="logo">O</div><div><b>Ozon Аналитика</b><small>Центр управления</small></div></div><nav>{nav.map(([n,I])=><button className={page===n?'active':''} onClick={()=>setPage(n)} key={n}><I size={19}/><span>{n}</span>{page===n&&<i/>}</button>)}</nav><div className="aside-bottom"><div className="sync"><div className="sync-icon"><Cloud size={18}/><span/></div><div><b>Демо-режим</b><small>Данные из Excel</small></div></div><div className="profile"><div className="avatar">АП</div><div><b>Алексей Петров</b><small>Администратор</small></div><MoreHorizontal size={18}/></div></div></aside>}
function Header({page,onExpense,onExport,onSettings,notify}){return <><header><div><h1>{page}</h1><p>{page==='Главная'?'Обзор ключевых показателей вашего бизнеса':page==='Ежедневный контроль'?'Продажи, расходы и прибыль по товарам':'Каталог и параметры прибыльности товаров'}</p></div><div className="actions"><button className="icon-btn" onClick={onSettings}><Settings size={19}/></button><button className="secondary" onClick={onExport}><Download size={18}/>Экспорт Excel</button><button className="primary" onClick={onExpense}><Plus size={18}/>Добавить расход</button></div></header><div className="demo-banner"><FileSpreadsheet size={18}/><span><b>Демо — данные из Excel.</b> Показатели не получены из Ozon.</span><button onClick={()=>notify('Данные актуальны') }><RefreshCw size={15}/>Обновить</button></div></>}
function Dashboard({extra}){const profit=22740.55-(extra-23010);const cards=[['Выручка','627 729,15 ₽','−3,38%','red',WalletCards],['Чистая прибыль',fmt(profit),'−10,40%','red',TrendingUp],['Продано','678 шт.','−1,74%','red',ShoppingBag],['Маржа',pct(profit/627729.15*100),'−0,28 п.п.','red',Percent],['ДРР','13,04%','−0,55 п.п.','green',Target]];return <div className="content"><div className="toolbar"><button className="date"><CalendarDays size={17}/>2 июля 2026<ChevronDown size={16}/></button><div className="presets"><button>Сегодня</button><button>Вчера</button><button className="selected">7 дней</button><button>Месяц</button></div><span className="status"><span/>Демо-данные</span></div><section className="kpis">{cards.map(([l,v,c,cl,I])=><article className="kpi" key={l}><div className="kpi-top"><span>{l}</span><div className="kpi-icon"><I size={19}/></div></div><strong>{v}</strong><div className={'change '+cl}>{cl==='green'?<TrendingDown/>:<TrendingDown/>}{c} <em>к 1 июля</em></div>{l==='Чистая прибыль'&&<small className="pre">● предварительно</small>}</article>)}</section><div className="grid"><Chart/><Attention/><Leaders/></div></div>}
function Chart(){return <article className="panel chart-panel"><div className="panel-head"><div><h2>Выручка и прибыль по дням</h2><p>Динамика за выбранный период</p></div><div className="legend"><span><i className="blue"/>Выручка</span><span><i className="green-dot"/>Прибыль</span></div></div><div className="chart"><div className="ylabels"><span>700 тыс.</span><span>525 тыс.</span><span>350 тыс.</span><span>175 тыс.</span><span>0</span></div><svg viewBox="0 0 700 230" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#1677ff" stopOpacity=".22"/><stop offset="1" stopColor="#1677ff" stopOpacity="0"/></linearGradient></defs><g className="lines"><path d="M0 20H700M0 70H700M0 120H700M0 170H700M0 220H700"/></g><path className="area" d="M20 38 C170 32,220 43,350 44 S550 50,680 47 L680 220L20 220Z"/><path className="revenue-line" d="M20 38 C170 32,220 43,350 44 S550 50,680 47"/><path className="profit-line" d="M20 194 C170 190,220 193,350 194 S550 197,680 196"/><circle cx="20" cy="38" r="5"/><circle cx="680" cy="47" r="5"/></svg><div className="xlabels"><span>1 июл</span><span>2 июл</span></div><div className="tip"><b>2 июля</b><span>Выручка <strong>627 729 ₽</strong></span><span>Прибыль <strong>22 741 ₽</strong></span></div></div></article>}
function Attention(){return <article className="panel attention"><div className="panel-head"><div><h2>Требует внимания</h2><p>4 сигнала за период</p></div><button className="link">Все сигналы <ArrowUpRight size={15}/></button></div><div className="alerts"><Alert color="red" icon={TrendingDown} title="2 товара работают в минус" sub="Потери 1 358,70 ₽"/><Alert color="orange" icon={Target} title="ДРР выше 20%" sub="У 3 товаров"/><Alert color="yellow" icon={TriangleAlert} title="Не заполнена себестоимость" sub="1 товар требует настройки"/><Alert color="blue" icon={Unlink} title="Не связано с Ozon" sub="2 SKU не сопоставлены"/></div></article>}
function Alert({color,icon:I,title,sub}){return <div className="alert"><div className={'alert-icon '+color}><I size={17}/></div><div><b>{title}</b><small>{sub}</small></div><ChevronRight size={17}/></div>}
function Leaders(){return <article className="panel leaders"><div className="panel-head"><div><h2>Эффективность товаров</h2><p>По чистой прибыли за 2 июля</p></div><div className="toggle"><button className="on">Лидеры</button><button>Аутсайдеры</button></div></div><table><thead><tr><th>ТОВАР</th><th>ПРОДАНО</th><th>ПРИБЫЛЬ</th><th>МАРЖА</th></tr></thead><tbody>{products.slice(0,5).map((p,i)=><tr key={p.sku}><td><span className="rank">{i+1}</span><div><b>{p.name}</b><small>SKU {p.sku}</small></div></td><td>{p.sold} шт.</td><td><b>{fmt(p.profit)}</b></td><td><span className="margin">{pct(p.margin)}</span></td></tr>)}</tbody></table></article>}
function Daily({tab,setTab}){const[search,setSearch]=useState('');const[remote,setRemote]=useState(null);useEffect(()=>{const timer=setTimeout(()=>api.daily('2026-07-02',search).then(setRemote).catch(()=>setRemote(null)),150);return()=>clearTimeout(timer)},[search]);const rows=remote?.items||products.filter(p=>(p.name+p.sku).toLowerCase().includes(search.toLowerCase()));return <div className="content"><div className="tabs"><button className={tab==='Товары'?'on':''} onClick={()=>setTab('Товары')}>Товары</button><button className={tab==='Расходы'?'on':''} onClick={()=>setTab('Расходы')}>Расходы <span>7</span></button></div><div className="filterbar"><button className="date"><CalendarDays size={17}/>2 июля 2026<ChevronDown size={16}/></button><label className="search"><Search size={17}/><input placeholder="Название или SKU" value={search} onChange={e=>setSearch(e.target.value)}/></label><button>Все схемы <ChevronDown size={15}/></button><button><SlidersHorizontal size={16}/>Фильтры</button></div>{tab==='Товары'?<DataTable rows={rows} totals={remote?.totals}/>:<Expenses/>}</div>}
function DataTable({rows,totals}){const t=totals||{sku_count:34,sold:678,revenue:627729.15,ads:81876,drr:13.04,extra_costs:23010,profit:22740.55,margin:3.62};return <article className="panel data"><table><thead><tr><th>ТОВАР И SKU</th><th>СХЕМА</th><th>ПРОДАНО</th><th>ВЫРУЧКА <small>API</small></th><th>РЕКЛАМА <small className="manual">РУЧНОЙ</small></th><th>ДРР</th><th>ДОП. РАСХОДЫ</th><th>ЧИСТАЯ ПРИБЫЛЬ</th><th>МАРЖА</th><th>СТАТУС</th></tr></thead><tbody>{rows.map(p=><tr key={p.sku}><td><div><b>{p.name}</b><small>SKU {p.sku}</small></div></td><td><span className="scheme">{p.scheme}</span></td><td>{p.sold}</td><td>{fmt(p.revenue)}</td><td><button className="edit">{fmt(p.ads)}</button></td><td>{pct(p.drr??p.ads/p.revenue*100)}</td><td>{fmt(p.extra_costs??p.extra)}</td><td className={p.profit<0?'negative':''}><b>{fmt(p.profit)}</b></td><td>{pct(p.margin)}</td><td><span className="demo-pill">Демо</span></td></tr>)}</tbody><tfoot><tr><td><b>Итого · {t.sku_count} SKU</b></td><td></td><td><b>{t.sold}</b></td><td><b>{fmt(t.revenue)}</b></td><td><b>{fmt(t.ads)}</b></td><td><b>{pct(t.drr)}</b></td><td><b>{fmt(t.extra_costs)}</b></td><td><b>{fmt(t.profit)}</b></td><td><b>{pct(t.margin)}</b></td><td/></tr></tfoot></table></article>}
function Expenses(){return <article className="panel data"><table><thead><tr><th>ДАТА</th><th>ТИП</th><th>ТОВАР</th><th>СУММА</th><th>КОММЕНТАРИЙ</th><th>АВТОР</th></tr></thead><tbody>{products.slice(0,5).map((p,i)=><tr><td>02.07.2026</td><td><span className="scheme">{i%2?'Доп. расход':'Реклама'}</span></td><td>{p.name}</td><td><b>{fmt(i%2?p.extra:p.ads)}</b></td><td className="muted">Импортировано из Excel</td><td>Система</td></tr>)}</tbody></table></article>}
function Catalog(){return <div className="content"><section className="mini-kpis"><div><span>Активных SKU</span><b>34</b></div><div><span>Связано с Ozon</span><b>32</b><small>94%</small></div><div><span>Без себестоимости</span><b className="warn">1</b></div><div><span>Маржа ниже порога</span><b className="bad">4</b></div></section><div className="filterbar"><label className="search"><Search size={17}/><input placeholder="Найти товар или SKU"/></label><button>Статус связи <ChevronDown size={15}/></button><button><SlidersHorizontal size={16}/>Фильтры</button></div><article className="panel data"><table><thead><tr><th>ТОВАР</th><th>SKU / OFFER_ID</th><th>OZON PRODUCT ID</th><th>ЦЕНА</th><th>СЕБЕСТОИМОСТЬ</th><th>ЧИСТЫМИ С ПРОДАЖИ</th><th>БАЗОВАЯ МАРЖА</th><th>ROI</th><th>СВЯЗЬ С OZON</th></tr></thead><tbody>{products.map(p=><tr><td><div><b>{p.name}</b><small>{p.scheme}</small></div></td><td><code>{p.sku}</code></td><td className="muted">{p.link==='Связан'?'—':'Не задан'}</td><td>{fmt(p.price)}</td><td>{p.cost?fmt(p.cost):<span className="bad-text">Не заполнена</span>}</td><td>{fmt(p.price-(p.cost||0)-430)}</td><td>{pct(p.margin+8)}</td><td>{p.roi?pct(p.roi):'—'}</td><td><span className={p.link==='Связан'?'linked':'unlinked'}>{p.link==='Связан'?<Link2 size={13}/>:<Unlink size={13}/>} {p.link}</span></td></tr>)}</tbody></table></article></div>}
function Modal({children,close,title,sub}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modal-head"><div><h2>{title}</h2><p>{sub}</p></div><button onClick={close}><X/></button></div>{children}</div></div>}
function ExpenseModal({close,save}){const[value,setValue]=useState('');return <Modal close={close} title="Добавить расход" sub="Показатели пересчитаются после сохранения"><div className="form"><label>Дата<input type="date" defaultValue="2026-07-02"/></label><label>Тип расхода<select><option>Реклама</option><option>Дополнительный расход</option></select></label><label>Сумма, ₽<input autoFocus type="number" placeholder="0,00" value={value} onChange={e=>setValue(e.target.value)}/></label><label>Товар <small>необязательно</small><select><option>Общий расход за день</option>{products.map(p=><option>{p.name}</option>)}</select></label><label className="full">Комментарий<textarea placeholder="Например, съёмка контента"/></label></div><div className="modal-actions"><button onClick={close}>Отмена</button><button className="primary" disabled={!value} onClick={()=>save(value)}>Сохранить и пересчитать</button></div></Modal>}
function SettingsModal({close,notify}){const[clientId,setClientId]=useState('');const[key,setKey]=useState('');const[busy,setBusy]=useState(false);const connect=async()=>{setBusy(true);try{await api.connect({client_id:clientId,api_key:key});notify('Кабинет Ozon подключён');close()}catch(e){notify(e.message)}finally{setBusy(false)}};return <Modal close={close} title="Подключение Ozon" sub="Seller API · только чтение"><div className="connection"><div className="conn-status"><div><span className="bigdot"/><b>Демо-режим</b><small>Подключите кабинет для получения живых данных</small></div></div><div className="form"><label>Client ID<input value={clientId} onChange={e=>setClientId(e.target.value)} placeholder="Введите Client ID"/></label><label>API Key<input value={key} onChange={e=>setKey(e.target.value)} type="password" placeholder="••••••••••••••••"/></label></div><div className="secure">🔒 API-ключ хранится только на сервере и не передаётся в браузер.</div></div><div className="modal-actions"><button onClick={close}>Отмена</button><button className="primary" disabled={busy||!clientId||!key} onClick={connect}>{busy?'Проверяем…':'Проверить подключение'}</button></div></Modal>}
createRoot(document.getElementById('root')).render(<App/>);
